/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectolbd;

import DBA.DBConnection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import modelos.Antena;
import modelos.Quickpass;
import modelos.Tarifas;
import modelos.Usuario;

/**
 *
 * @author danny
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    DBConnection conexion;
    ArrayList<Usuario> usuarios;
    ArrayList<Quickpass> usuarioActualQuickpasses;
    ArrayList<Antena> antenas;
    DefaultListModel<String> listUsuarioModel;
    DefaultComboBoxModel<String> comboxQuickpassModel;
    DefaultComboBoxModel<String> comboxAntenaModel;

    public frmMenuPrincipal() {
        initComponents();
        panelInfoUsuario.setVisible(false);
        conexion = new DBConnection();
        listUsuarioModel = new DefaultListModel<>();
        listUsuarios.setModel(listUsuarioModel);
        comboxQuickpassModel = new DefaultComboBoxModel<>();
        comboxAntenaModel = new DefaultComboBoxModel<>();
        llenarListaUsuarios();
        mostrarAntenas();
    }

    private void llenarListaUsuarios() {
        usuarios = conexion.getUsuarios();

        for (Usuario usuario : usuarios) {
            listUsuarioModel.addElement(usuario.getNombre());
        }
    }

    private void mostrarInfoUsuario(Usuario usuario) {
        panelInfoUsuario.setVisible(true);
        usuarioActualQuickpasses = conexion.getQuickpass(usuario.getIdUsuario());
        comboxQuickpass.setModel(comboxQuickpassModel);

        comboxQuickpassModel.removeAllElements();

        for (Quickpass quickpass : usuarioActualQuickpasses) {
            comboxQuickpassModel.addElement("ID: "+quickpass.getIdQuickpass()+" - "+quickpass.getNombreBanco());
        }
    }

    private void mostrarAntenas() {
        antenas = conexion.getAntena();
        comboxAntena.setModel(comboxAntenaModel);

        for (Antena antena : antenas) {
            comboxAntenaModel.addElement(antena.getRutaPeaje() + " (" + antena.getIdAntena() + ")");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainBG = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsuarios = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelInfoUsuario = new javax.swing.JPanel();
        comboxQuickpass = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnProcesar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTarifas = new javax.swing.JLabel();
        comboxAntena = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        mainBG.setBackground(new java.awt.Color(51, 255, 102));
        mainBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));

        listUsuarios.setBackground(new java.awt.Color(204, 255, 204));
        listUsuarios.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        listUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listUsuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listUsuariosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listUsuarios);

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setText("Usuarios");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        mainBG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 410));

        panelInfoUsuario.setBackground(new java.awt.Color(51, 255, 102));

        comboxQuickpass.setBackground(new java.awt.Color(51, 255, 153));
        comboxQuickpass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxQuickpass.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel1.setText("Quickpass");

        btnProcesar.setBackground(new java.awt.Color(0, 204, 102));
        btnProcesar.setText("Procesar");
        btnProcesar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 0)));
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("¡Bienvenido!");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rfid.png"))); // NOI18N

        javax.swing.GroupLayout panelInfoUsuarioLayout = new javax.swing.GroupLayout(panelInfoUsuario);
        panelInfoUsuario.setLayout(panelInfoUsuarioLayout);
        panelInfoUsuarioLayout.setHorizontalGroup(
            panelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoUsuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxQuickpass, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelInfoUsuarioLayout.setVerticalGroup(
            panelInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoUsuarioLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(comboxQuickpass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        mainBG.add(panelInfoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 250, 410));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel3.setText("Antenas");

        comboxAntena.setBackground(new java.awt.Color(0, 102, 102));
        comboxAntena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxAntena.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        comboxAntena.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxAntenaItemStateChanged(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/peaje.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(comboxAntena, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblTarifas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(comboxAntena, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(lblTarifas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        mainBG.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 230, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listUsuariosValueChanged
        // TODO add your handling code here:
        int idUsuarioSeleccionado = evt.getFirstIndex();

        if (idUsuarioSeleccionado >= 0 && idUsuarioSeleccionado < usuarios.size()) {
            mostrarInfoUsuario(usuarios.get(idUsuarioSeleccionado));
        }
    }//GEN-LAST:event_listUsuariosValueChanged

    private void comboxAntenaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxAntenaItemStateChanged
        // TODO add your handling code here:
        System.out.println("proyectolbd.frmMenuPrincipal.comboxAntenaItemStateChanged()" + evt.getItem());
        int antenaSeleccionada = comboxAntena.getSelectedIndex();

        // Validar que el índice es válido
        if (antenaSeleccionada >= 0 && antenaSeleccionada < antenas.size()) {
            // Obtener el objeto correspondiente del ArrayList
            Antena antena = antenas.get(antenaSeleccionada);

            // Mostrar información o realizar acciones
            mostrarTarifas(antena.getIdAntena());
        }
    }//GEN-LAST:event_comboxAntenaItemStateChanged

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
        int antenaSeleccionada = comboxAntena.getSelectedIndex();
        int quickpassSeleccionado = comboxQuickpass.getSelectedIndex();

        Antena antena = null;
        Quickpass quickpass = null;
        // Validar que el índice es válido
        if (antenaSeleccionada >= 0 && antenaSeleccionada < antenas.size()) {
            // Obtener el objeto correspondiente del ArrayList
            antena = antenas.get(antenaSeleccionada);
        }

        if (quickpassSeleccionado >= 0 && quickpassSeleccionado < usuarioActualQuickpasses.size()) {
            // Obtener el objeto correspondiente del ArrayList
            quickpass = usuarioActualQuickpasses.get(quickpassSeleccionado);
        }

        if (antena != null && quickpass != null) {
            procesarPase(antena, quickpass);
        }

    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JComboBox<String> comboxAntena;
    private javax.swing.JComboBox<String> comboxQuickpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTarifas;
    private javax.swing.JList<String> listUsuarios;
    private javax.swing.JPanel mainBG;
    private javax.swing.JPanel panelInfoUsuario;
    // End of variables declaration//GEN-END:variables

    private void mostrarTarifas(int idAntena) {
        lblTarifas.setVisible(false);
        ArrayList<Tarifas> tarifas = conexion.getMontoAntena(idAntena);

        String tarifasString = "<html>TARIFAS<br>";
        for (Tarifas tarifa : tarifas) {
            tarifasString += tarifa.getDescripcionTipoVehiculo() + " > $" + tarifa.getMonto() + "<br>";
        }
        tarifasString += "</html>";

        lblTarifas.setText(tarifasString);
    }

    private void procesarPase(Antena antena, Quickpass quickpass) {
        int resultado = conexion.procesarPase(antena.getIdAntena(), quickpass.getIdQuickpass());
        switch (resultado) {
            case 1:
                lblResultado.setText("<html>RECHAZADA<br>Su QuickPass no puede ser encontrado en los peajes</html>");
                break;
            case 2:
                lblResultado.setText("<html>RECHAZADA.<br>Su QuickPass está inactivo, por favor contacte a su proveedor</html>");
                break;
            case 3:
                lblResultado.setText("<html>RECHAZADO.<br>EL tipo de Vehiculo no fue encontrado, contacte a su proveedor</html>");
                break;
            case 4:
                lblResultado.setText("<html>RECHAZADO.<br>No se puede encontrar el costo del peaje</html>");
                break;
            case 5:
                lblResultado.setText("<html>PASE AUTORIZADO.<br>Que disfrute su día, y maneje con cuidado</html>");
                break;
            case 6:
                lblResultado.setText("<html>PASE RECHAZADO</html>");
                break;
            case -1:
                lblResultado.setText("<html>Error de conexion</html>");
                break;
            default:
                throw new AssertionError();
        }
    }

}
